add permission check

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -33,6 +33,17 @@ jobs:
           echo "Version found: $version"
           echo "##[set-output name=version;]$version"
 
+      - name: Check GITHUB_TOKEN permissions
+        id: check_permissions
+        run: |
+          PERMISSIONS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/permissions)
+          if [[ $PERMISSIONS != *"create_release"* ]]; then
+            echo -e "\033[0;31mError: GITHUB_TOKEN does not have create_release permission\033[0m"
+            echo -e "\033[0;31mSOLUTION: Please Enter https://github.com/${{ github.repository }}/settings/actions and update \"Workflow permissions\"\033[0m"
+            echo -e "\033[0;31mto \"Read and write permission\" for \"Read and write permissions\"\033[0m"
+            exit 1
+          fi
+
       - name: Create GitHub Release
         id: create_release
         uses: actions/create-release@v1
@@ -43,17 +54,6 @@ jobs:
           release_name: Release ${{ steps.get_version.outputs.version }}
           draft: false
           prerelease: false
-
-      - name: Check GITHUB_TOKEN permissions
-        id: check_permissions
-        run: |
-          PERMISSIONS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/permissions)
-          if [[ $PERMISSIONS != *"create_release"* ]]; then
-            echo -e "\033[0;31mError: GITHUB_TOKEN does not have create_release permission\033[0m"
-            echo -e "\033[0;31mSOLUTION: Please Enter Repo Settings > Actions and update \"Workflow permissions\"\033[0m"
-            echo -e "\033[0;31mto \"Read and write permission\" for \"Read and write permissions\"\033[0m"
-            exit 1
-          fi
 
       - name: Upload Release Assets
         if: steps.check_permissions.outputs.success == 'true'
